/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolsimRouteImport } from './routes/solsim'
import { Route as ReciparooRouteImport } from './routes/reciparoo'
import { Route as ImagarooRouteImport } from './routes/imagaroo'
import { Route as DidjyahRouteImport } from './routes/didjyah'
import { Route as ClassclarusRouteImport } from './routes/classclarus'
import { Route as IndexRouteImport } from './routes/index'

const SolsimRoute = SolsimRouteImport.update({
  id: '/solsim',
  path: '/solsim',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciparooRoute = ReciparooRouteImport.update({
  id: '/reciparoo',
  path: '/reciparoo',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagarooRoute = ImagarooRouteImport.update({
  id: '/imagaroo',
  path: '/imagaroo',
  getParentRoute: () => rootRouteImport,
} as any)
const DidjyahRoute = DidjyahRouteImport.update({
  id: '/didjyah',
  path: '/didjyah',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassclarusRoute = ClassclarusRouteImport.update({
  id: '/classclarus',
  path: '/classclarus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classclarus': typeof ClassclarusRoute
  '/didjyah': typeof DidjyahRoute
  '/imagaroo': typeof ImagarooRoute
  '/reciparoo': typeof ReciparooRoute
  '/solsim': typeof SolsimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classclarus': typeof ClassclarusRoute
  '/didjyah': typeof DidjyahRoute
  '/imagaroo': typeof ImagarooRoute
  '/reciparoo': typeof ReciparooRoute
  '/solsim': typeof SolsimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classclarus': typeof ClassclarusRoute
  '/didjyah': typeof DidjyahRoute
  '/imagaroo': typeof ImagarooRoute
  '/reciparoo': typeof ReciparooRoute
  '/solsim': typeof SolsimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classclarus'
    | '/didjyah'
    | '/imagaroo'
    | '/reciparoo'
    | '/solsim'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/classclarus' | '/didjyah' | '/imagaroo' | '/reciparoo' | '/solsim'
  id:
    | '__root__'
    | '/'
    | '/classclarus'
    | '/didjyah'
    | '/imagaroo'
    | '/reciparoo'
    | '/solsim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassclarusRoute: typeof ClassclarusRoute
  DidjyahRoute: typeof DidjyahRoute
  ImagarooRoute: typeof ImagarooRoute
  ReciparooRoute: typeof ReciparooRoute
  SolsimRoute: typeof SolsimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solsim': {
      id: '/solsim'
      path: '/solsim'
      fullPath: '/solsim'
      preLoaderRoute: typeof SolsimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reciparoo': {
      id: '/reciparoo'
      path: '/reciparoo'
      fullPath: '/reciparoo'
      preLoaderRoute: typeof ReciparooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagaroo': {
      id: '/imagaroo'
      path: '/imagaroo'
      fullPath: '/imagaroo'
      preLoaderRoute: typeof ImagarooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/didjyah': {
      id: '/didjyah'
      path: '/didjyah'
      fullPath: '/didjyah'
      preLoaderRoute: typeof DidjyahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classclarus': {
      id: '/classclarus'
      path: '/classclarus'
      fullPath: '/classclarus'
      preLoaderRoute: typeof ClassclarusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassclarusRoute: ClassclarusRoute,
  DidjyahRoute: DidjyahRoute,
  ImagarooRoute: ImagarooRoute,
  ReciparooRoute: ReciparooRoute,
  SolsimRoute: SolsimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
